Hacer la vista de crear usuario
FernandoJoachin/bienes-raices-const-sw pull request #19
Opened 2023-11-07 10:42 UTC by FernandoJoachin

Closes #9

2023-11-07 21:26 UTC, CarlosMay7 commented on vistas/usuarios/crear.php
> +  <h1>Crear Usuario(a)</h1>
```suggestion
  <h1>Crear Usuario</h1>
```
Creo que no es necesario agregarlo ya que usuario es un objeto como tal

2023-11-07 21:28 UTC, CarlosMay7 requested changes
Muy bien pero observé un cambio mínimo

2023-11-07 21:28 UTC, CarlosMay7 commented on vistas/usuarios/crear.php
> +    <input type="submit" value="Crear Usuario(a)" class="boton boton-verde">
```suggestion
    <input type="submit" value="Crear Usuario" class="boton boton-verde">
```
Igual aquí

2023-11-07 23:11 UTC, CarlosMay7 approved these changes

2023-11-08 00:18 UTC, Oswaldo-Chan approved these changes

2023-11-08 00:24 UTC, merged